import type { BlogPost } from "@/data/blog/types";

export const post: BlogPost = {
  slug: "taqwa-lock-mindful-app-blocker-case-study",
  title:
    "Taqwa Lock: Building an App Blocker That Never Reads What You Type",
  seoTitle: "Taqwa Lock Case Study: Privacy by Design",
  description:
    "How we built a local-first app blocker using platform screen-time APIs, with a review process that keeps AI out of religious content entirely.",
  excerpt:
    "An app blocker needs to know which app is in front of you. Almost every technique for finding that out can also read your messages. We picked the one that cannot.",
  category: "Case Studies",
  primaryKeyword: "app blocker privacy design",
  secondaryKeywords: [
    "android accessibility service app blocker",
    "ios family controls development",
    "local first mobile app",
    "screen time api development",
  ],
  published: "2026-08-13",
  authorId: "leadership-02",
  serviceSlug: "mobile-app-development",
  keyTakeaway:
    "Taqwa Lock pauses a user before a distracting app, offers a short reviewed reflection, then grants a limited access window. It is local-first and needs no account, and the core loop works offline. The defining constraints are two refusals: the Android service reads package names only and never view content, keystrokes, URLs or form data, and religious content is never generated by a model, requiring a cleared licence, a source locator and two independent reviewers before it ships.",
  sections: [
    {
      heading: "The short version",
      blocks: [
        {
          type: "p",
          text: "Choose the apps that pull you away. When you open one, the app interrupts with a short reflection. Complete it and you get a limited access window for that app, then the pause returns.",
        },
        {
          type: "p",
          text: "No account is required. The protection loop stays available offline. The core loop, the bundled reminders, the privacy controls and the local statistics are never behind a paywall.",
        },
        {
          type: "callout",
          text: "A blocker that stops working when the network drops is not a blocker. It is a suggestion.",
        },
      ],
    },
    {
      heading: "The privacy problem at the centre of every blocker",
      blocks: [
        {
          type: "p",
          text: "To interrupt someone before a distracting app, you must know which app is in the foreground. On Android the usual route is an accessibility service, and an accessibility service is one of the most powerful permissions the platform offers. It can read view content, observe gestures, capture keystrokes, see URLs, read messages and read form data.",
        },
        {
          type: "p",
          text: "Most blockers take that permission and then promise, in a privacy policy, not to misuse it. That is a promise made in a document about a capability that exists in the binary.",
        },
        {
          type: "h3",
          text: "The narrower option",
        },
        {
          type: "p",
          text: "The service here is package-only. It observes which application is in front and nothing else. View content retrieval, gestures, keystrokes, URLs, messages and form data are not accessed at all.",
        },
        {
          type: "p",
          text: "On iOS the equivalent work uses the platform screen-time frameworks: family controls, managed settings, a custom shield extension and a device activity monitor. App selections are handled as opaque tokens, so the app never learns which specific applications the user chose, only that a selection exists to enforce.",
        },
        {
          type: "p",
          text: "The iOS design is a useful illustration of a general point. The platform gave a way to enforce a rule without revealing the data behind it, and taking that route costs some flexibility and removes an entire class of risk.",
        },
      ],
    },
    {
      heading: "Content that a model is not allowed to write",
      blocks: [
        {
          type: "p",
          text: "The reflection shown during a pause is religious content. The rule is that it is never generated by AI.",
        },
        {
          type: "p",
          text: "Every production entry requires a cleared translation licence, a source locator identifying exactly where it came from, and two independent reviewers. There is a review-gated content schema in the codebase with validation and selection logic, so an unreviewed entry cannot reach a user by accident.",
        },
        {
          type: "h3",
          text: "Why build machinery for this",
        },
        {
          type: "p",
          text: "Because a policy that lives only in someone's head is one busy week away from being broken. Encoding review state in the schema means the constraint is enforced by the type system and the validator rather than by everyone remembering.",
        },
        {
          type: "p",
          text: "This generalises well beyond religious text. Any product with medical, legal or financial content has the same shape of problem, and the same answer applies: make the unreviewed state unrepresentable in production.",
        },
      ],
    },
    {
      heading: "What stays free, and why that is an engineering decision",
      blocks: [
        {
          type: "p",
          text: "The protection loop, the bundled reviewed reminders, the privacy controls and the local statistics are never paywalled. Managed backend, analytics, diagnostics and billing are all optional services, and missing network configuration never disables the offline core.",
        },
        {
          type: "p",
          text: "That is a commercial commitment with an architectural consequence. It means the core cannot depend on a server, which forces local-first storage and a genuine offline path rather than a cached approximation of one.",
        },
        {
          type: "list",
          items: [
            "Native Android work handles the service and reboot-safe per-app sessions, because a blocker that forgets its state after a restart is trivially defeated.",
            "iOS extensions cover the shield configuration, the shield action and device activity monitoring.",
            "Edge functions handle content manifests, review assistance, data deletion and billing webhooks.",
            "A release preflight verifier fails closed before a production build is produced.",
          ],
        },
      ],
    },
    {
      heading: "What we would tell you if you were building this",
      blocks: [
        {
          type: "list",
          ordered: true,
          items: [
            "Take the narrowest permission that does the job, even when the broader one is easier. You are going to have to explain the permission during store review and to every privacy-conscious user, and narrow is much easier to explain.",
            "Encode editorial rules in the schema. If unreviewed content cannot be represented in a production build, nobody has to remember the rule at 11pm before a release.",
            "Decide what is never paywalled before you build. It constrains the architecture in useful ways and it stops the free tier from decaying feature by feature.",
            "Test the reboot path. Any always-on protection that does not survive a restart provides the appearance of protection only.",
          ],
        },
      ],
    },
  ],
  faqs: [
    {
      question: "Why is an accessibility service a privacy concern?",
      answer:
        "Because it is one of the most powerful permissions Android grants. It can read view content, keystrokes, URLs, messages and form data. The service here is deliberately package-only: it observes which app is in the foreground and accesses none of the rest.",
    },
    {
      question: "How does app blocking work on iOS?",
      answer:
        "Through the platform screen-time frameworks: family controls, managed settings, a custom shield extension and a device activity monitor. App selections are opaque tokens, so the app can enforce a rule without ever learning which specific apps were chosen.",
    },
    {
      question: "Why not use AI to generate the reflection content?",
      answer:
        "Because it is religious text, where accuracy and provenance matter more than volume. Every production entry needs a cleared translation licence, a source locator and two independent reviewers, and the review state is enforced by the content schema rather than by policy alone.",
    },
    {
      question: "Does the app work without an internet connection?",
      answer:
        "Yes. It is local-first and requires no account. Backend services, analytics, diagnostics and billing are all optional, and missing network configuration never disables the core protection loop or the bundled reminders.",
    },
    {
      question: "What stops a user simply restarting the phone to get around it?",
      answer:
        "Per-app sessions are reboot-safe, handled in native Android code. An always-on protection that forgets its state after a restart offers the appearance of protection rather than the thing itself.",
    },
  ],
};
